version: "3.8"

services:
    mysql:
        image: mysql:8.3
        restart: unless-stopped
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        ports:
            - 3306:3306

volumes:
    mysql-data:
